### PR TITLE
feat: write_traceability_matrix: put test IDs in same cell

### PR DESCRIPTION
**Pull request by kyleam**
write_traceability_matrix() generates a table with user stories and
test IDs.  The same user story can span multiple rows, with the test
ID changing.  In this case, the repeated user story is left blank to
make the grouping stand out.

A downside of this approach is that the story is spread across
multiple rows and can't be easily highlighted by simple borders or
alternating colors (which could be done via a reference docx style).

To make this possible, instead put all the test IDs into the same
cell.  This has the disadvantage that the row needs to be manually
resized after the fact so that each test ID is on its own
line.  **But** this is already the case: cells with a single ID are
being broken across multiple lines, and I haven't found a way to fix
that (including trying the pander package).  So, if we're going to
need to manually resize the column anyway, we might as well use a
single row so that the groups can be easily styled.

### CODE REVIEW

**Comment by seth127** [comment]
I see the appeal here. I think we should send both options to Aing. Here are some screenshots we can use:

**Option 1:**
Screen Shot 2021-08-06 at 10 31 27 AM

**Option 2:**
Screen Shot 2021-08-06 at 10 30 32 AM

**Comment by seth127** [comment]
also @kyleam if we go with this option, we should probably comma-separate those ID's

**Comment by kyleam** [comment]
> Here are some screenshots we can use:

Just a note: a large part of the case I'm making for the second one is that *for either option 1 or 2 the columns need to be manually resized* (at least that's the case on my end).  So I'm proposing the second option have IDs all on separate lines (will edit with a screenshot).

**Comment by seth127** [comment]
ahhh I see. I've updated the screenshots above. I do think that looks better.

**Review by seth127 — APPROVED** [review]
If we're gonna need to manually adjust anyway, this looks a lot better

**Comment by kyleam** [comment]
I've merged dev/metworx_refactor to resolve conflicts with the recently merged dev/fixing_legacy_functionality.

**Pull request merged**
