### PR TITLE
feat: create_validation_docs: support docx style references

### PR DESCRIPTION
**Pull request by kyleam**
The generated documents require various manual tweaks.  Some of these
(e.g., table styling and custom headers and footers) can instead be
handled automatically by specifying a custom style reference (via
Pandoc's `--reference-doc`).

Let the caller specify styles for the generated validation docs by
pointing to a directory that contains reference documents with
matching base names.

### CODE REVIEW

**Review by seth127 — COMMENTED** [review]
I love this. One thought though: should we include some formatting template in `inst` do be able to easily point to? The most obvious ones would be... the ones we're using. **Pro:** it would make it easier to render the docs. **Con:** it has Metrum branding on it and this is a public repo. Not that our branding is _private_ but for things like `templ` we choose _not_ to expose this kind of stuff. Thoughts @dpastoor ?

**Comment by kyleam** [comment]
> One thought though: [...]

Thanks for bringing that up.  If we do decide we should include them, I'd suggest adding them separately after the references settle.  I wouldn't be surprised if they change a bit while we work on the current submission.

**Comment by dpastoor** [comment]
my gut reaction would be could we put some placeholder templates in for purposes of testing that just dropped some of the most explicit parts of the branding (eg headers) but then still used whatever we have separately maintained for the doc generation. That way those templates themselves could evolve independently of the package as well

**Comment by kyleam** [comment]
> could we put some placeholder templates in for purposes of testing

Doing that for smoke tests sounds fine to me, though there's a gap/to-do right now in terms of testing doc generation (`create_validation_docs`, as well as the three underlying `write_*` functions).  I think it'd make sense to wire that up once the restructuring from `dev/fixing_legacy_functionality` lands.

**Review by seth127 — APPROVED** [review]
Nice stuff here. I think we should consider adding some example templates to `inst` or something but let's save that for a later date because any we would actually want to use have MRG branding on them and that's probably not that cool to include in a package.

**Comment by kyleam** [comment]
I've merged dev/metworx_refactor to resolve conflicts with the recently merged dev/fixing_legacy_functionality.

**Pull request merged**
