### PR TITLE
bug fix: dropping requirements with same tests

### LINKED ISSUE #89: Dropped requirements when using same test
The bug is that when multiple requirements are satisfied by the same test(s) and attached to the same story, only the first of them is included in the Requirements Specification document.

### PR DESCRIPTION
**Pull request by seth127**
Closes #89

### CODE REVIEW

**Comment by seth127** [comment]
The first commit adds a failing test and the second fixes the test (and the bug from #89)

For the others:

* [23ecfaa](https://github.com/metrumresearchgroup/mrgvalidate/pull/90/commits/23ecfaaf17c21dc05cc4a367d0af16b27299aeaf) and [3e840e9](https://github.com/metrumresearchgroup/mrgvalidate/pull/90/commits/3e840e98fa603dfbbe142478784d5ed43a8d3166) are semi-related cleanup
* [d6afa41](https://github.com/metrumresearchgroup/mrgvalidate/pull/90/commits/d6afa41f1eef5b384df8bef36f75b1c4e83cc2a9) is adding a test case for a similar potential bug (we don't currently have this bug, but we want to make sure it isn't introduced at some point)

**Comment by seth127** [comment]
screen shot of the isolated failure from the first commit, before the fix in the second:
Screenshot 2022-12-01 at 12 55 40 PM

**Comment by seth127** [comment]
@barrettk pinging you on here for visibility.

**Review by barrettk — APPROVED** [review]
Looks good to me. Tests pass on my end as well

**Pull request merged**
