### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by barrettk**
## New Features 
- Overhaul of entire package (is not backwards compatible).
 - Generated documents are now created from parameterized `rmarkdown` documents, instead of glueing text together.
 - There are a total of 7 validation documents (up from 3). The tracability matrix and requirements specification documents were carried over, but the other 5 are mostly new content.
 - `create_validation_docs` has been replaced by `create_package_docs()` and `create_metworx_docs()` for packages and the Metworx platform respectfully.
    - The arguments of these two functions are largely the same as `create_validation_docs`.
    - `create_package_docs()` has an added `language` argument, that will change the boilerplate text depending on the language the package was predominantly coded in.
 - Release notes are now required. This should contain two top-level headers for "Changes and New Features" and "Bug Fixes". For packages, this can typically be extracted from the relevant entry in the `NEWS.md` file.
 - More helpful warning and error messages.
 - `create_templates()` was introduced for easily creating templates for both packages and the Metworx platform.
 - More comprehensive test suite.
 
## Bug fixes
 - Missing links between requirements and stories were previously unreported. It will now error out if any are found.

### CODE REVIEW

**Comment by kyleam** [comment]
> create_package_docs() and create_metworx_docs() for packages and the Metworx platform respectfully

drive-by typo comment: respectively

**Comment by barrettk** [comment]
@seth127 mrgvalidate seems to be somewhat unstable for R 4.0.5. Going to investigate a bit, but wondering if we want to remove that check from drone

**Comment by barrettk** [comment]
FYI [submitted an issue](https://github.com/davidgohel/flextable/issues/457) on their GitHub

**Comment by seth127** [comment]
After discussion with group offline: given that the `flextable` maintainer has already responded to that issue, let's just sit on this release for a week or so and see if it gets fixed.

In the situation where it gets fixed before the next MPN snapshot, the bad version won't ever be on MPN, so I don't think we need to make any restrictions or accommodations in here.

**Review by seth127 — APPROVED** [review]
Looks like we're passing in drone now, so I think we're good to make this release.

Let's not forget to rebuild the pkdown docs and push to gh-pages too. Thanks @barrettk

**Pull request merged**
